version: 1.0.{build}
image:
  - Visual Studio 2019
  - Ubuntu1804
install:
  
before_build:
  - nuget restore ZigBeeNet.sln
build:
  publish_nuget: true
  verbosity: minimal
  project: ZigBeeNet.sln

deploy:
- provider: NuGet
  api_key:
    secure: 9VdEvjOY5m+yUTgytbM8ClNCwCqhUdz/iEpiuTHv3H9wQbg/YaIUwLLHzGis75P7
  skip_symbols: false
  artifact: /.*\.nupkg/

test:
  # only assemblies to test
  assemblies:
    - '**\*.test.dll'
